# Generated by Django 4.1.4 on 2022-12-28 19:33

import data.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('process_id', models.CharField(max_length=200)),
                ('data_name', models.CharField(max_length=500)),
                ('content', models.TextField()),
                ('data_path', models.FileField(upload_to=data.models.ProcessPath)),
                ('time', models.DateTimeField(default=datetime.datetime(2022, 12, 28, 19, 33, 2, 99546))),
            ],
            options={
                'unique_together': {('email', 'data_name')},
            },
        ),
        migrations.CreateModel(
            name='Experi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('type', models.IntegerField(choices=[(0, 'JV'), (1, 'XRD'), (2, 'IPCE'), (3, 'PL'), (4, 'ABS')])),
                ('test_time', models.CharField(max_length=200)),
                ('process_id', models.CharField(max_length=200)),
                ('sample_id', models.CharField(max_length=200)),
                ('data_name', models.CharField(max_length=500)),
                ('content', models.TextField()),
                ('data_path', models.FileField(upload_to=data.models.ExperiPath)),
                ('time', models.DateTimeField(default=datetime.datetime(2022, 12, 28, 19, 33, 2, 99546))),
                ('rank', models.IntegerField(choices=[(0, '未知'), (1, '一级好'), (2, '一般好'), (3, '一般'), (4, '不怎么好'), (5, '非常差')])),
                ('isPublic', models.BooleanField(default=False)),
                ('is_delete', models.BooleanField(default=False)),
            ],
            options={
                'unique_together': {('email', 'type', 'data_name')},
            },
        ),
    ]
