# Generated by Django 4.1.4 on 2023-01-04 14:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experi',
            name='rank',
            field=models.IntegerField(choices=[(0, '未知'), (5, '一级好'), (4, '一般好'), (3, '一般'), (2, '不怎么好'), (1, '非常差')]),
        ),
        migrations.AlterField(
            model_name='experi',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 4, 14, 12, 25, 655513)),
        ),
        migrations.AlterField(
            model_name='process',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 4, 14, 12, 25, 655513)),
        ),
    ]
