# Generated by Django 4.1.4 on 2022-12-28 19:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(0, '消息'), (1, '通知')])),
                ('send_id', models.CharField(max_length=500, null=True)),
                ('to_id', models.CharField(max_length=500, null=True)),
                ('content', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('time', models.DateTimeField(default=datetime.datetime(2022, 12, 28, 19, 33, 2, 101556))),
            ],
        ),
    ]
