# Generated by Django 4.1.4 on 2023-01-31 12:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0003_information_remove_message_type_alter_message_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('time', models.DateTimeField(default=datetime.datetime(2023, 1, 31, 12, 30, 15, 930609))),
            ],
        ),
        migrations.DeleteModel(
            name='Information',
        ),
        migrations.AlterField(
            model_name='message',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 31, 12, 30, 15, 930609)),
        ),
    ]
